-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 21:23:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stone` DEFAULT CHARACTER SET utf8 ;
USE `stone` ;

-- -----------------------------------------------------
-- Table `stone`.`faixasalarial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone`.`faixasalarial` (
  `id_faixasalarial` INT NOT NULL,
  `peso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_faixasalarial`));


-- -----------------------------------------------------
-- Table `stone`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone`.`Area` (
  `nome` VARCHAR(16) NOT NULL,
  `id_area` INT NOT NULL,
  `xid_faixasalarial` INT NULL,
  PRIMARY KEY (`id_area`),
  UNIQUE INDEX `id_area_UNIQUE` (`id_area` ASC) VISIBLE,
  INDEX `xid_faixasalarial_idx` (`xid_faixasalarial` ASC) VISIBLE,
  CONSTRAINT `xid_faixasalarial`
    FOREIGN KEY (`xid_faixasalarial`)
    REFERENCES `stone`.`faixasalarial` (`id_faixasalarial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stone`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone`.`Cargo` (
  `nome` VARCHAR(16) NOT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_cargo`));


-- -----------------------------------------------------
-- Table `stone`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stone`.`funcionario` (
  `nome` VARCHAR(16) NOT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `matricula` VARCHAR(45) NOT NULL,
  `xid-area` INT NOT NULL,
  `xid-cargo` INT NOT NULL,
  `salariobruto` VARCHAR(45) NOT NULL,
  INDEX `xid-area_idx` (`xid-area` ASC) VISIBLE,
  INDEX `xid-cargo_idx` (`xid-cargo` ASC) VISIBLE,
  CONSTRAINT `xid-area`
    FOREIGN KEY (`xid-area`)
    REFERENCES `stone`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `xid-cargo`
    FOREIGN KEY (`xid-cargo`)
    REFERENCES `stone`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
